import json
from pydantic import BaseModel, Field, ValidationError
from typing import List, Dict, Any, Optional, Tuple
from src.llm.client import llm_client
from src.utils.logger import get_logger

logger = get_logger(__name__)

# ==================== STRUCTURED RESPONSE SCHEMAS ====================

class HighLevelAnalysisPlan(BaseModel):
    """
    Strategic business analysis plan generated by the LLM.
    Decides what operations, metrics, and groupings are needed 
    to answer a business question without computing the calculations itself.
    """
    thought_process: str = Field(
        ..., 
        description="Detailed logical reasoning explaining why this specific analytical blueprint was mapped out."
    )
    analysis_plan: List[str] = Field(
        ..., 
        description="Ordered list of specific analytical steps to execute (e.g. ['trend_analysis', 'cohort_analysis', 'segment_comparison'])."
    )
    required_metrics: List[str] = Field(
        ..., 
        description="Calculations, KPIs, or numerical columns essential to this analysis (e.g. ['avg_data_usage_gb', 'churn_rate'])."
    )
    required_dimensions: List[str] = Field(
        ..., 
        description="Demographics, segments, or categorical grouping columns required for comparison (e.g. ['GEO_TAG', 'offer_tag'])."
    )
    suggested_visualizations: List[str] = Field(
        ..., 
        description="List of suggested Plotly representations to support this blueprint (e.g. ['Line chart of recharges over time'])."
    )
    recommended_statistical_tests: List[str] = Field(
        ...,
        description="List of recommended statistical tests to validate insights."
    )
    confidence_requirements: str = Field(
        ...,
        description="Required level of confidence for statistical tests (e.g. 'high', 'medium', 'low')."
    )

# ==================== MODULAR PROMPT TEMPLATE ====================

PLANNER_SYSTEM_PROMPT = """
You are a Lead Business Intelligence Architect and Strategic Data Consultant.
Your job is to convert complex business questions into a structured, highly focused Analysis Plan.

CRITICAL RULES:
1. DECISIONS ONLY: You must ONLY plan the strategy. You are FORBIDDEN from calculating metrics, estimating trends, or hallucinating results. Leave all computational logic to downstream Python solvers.
2. SCHEMA RIGIDITY: You must only plan to use columns, KPIs, and dimensions that are explicitly declared in the provided dataset metadata profile. Do not invent non-existent column fields.
3. CONTEXT INTEGRITY: Fully respect the business grain, KPIs, and descriptions supplied in the Context Layer.
"""

PLANNER_PROMPT_TEMPLATE = """
Dataset Contextual Profile:
{context_json}

User Business Question:
"{query}"

Please review the available columns, grains, and business KPIs above. Construct a structured, token-efficient HighLevelAnalysisPlan defining the strategic analyses, required metrics, required dimensions, and visualization suggestions.
"""

# ==================== VALIDATION LAYER ====================

def validate_plan_schema(plan: HighLevelAnalysisPlan, context_profile: Dict[str, Any]) -> Tuple[bool, List[str]]:
    """
    Validates that the dimensions and metrics planned by the LLM
    actually exist in the consolidated Contextual Profile.
    """
    logger.info("Validating planned dimensions and metrics against active dataset schema...")
    errors = []
    
    # 1. Gather all actual column names from all tables in the context profile
    available_cols = set()
    for table_name, table_info in context_profile.get("tables", {}).items():
        for col_name in table_info.get("columns", {}).keys():
            available_cols.add(col_name.strip().lower())
            
    # Also gather loaded KPI names
    available_kpis = set()
    for table_name, table_info in context_profile.get("tables", {}).items():
        for kpi in table_info.get("kpis", []):
            available_kpis.add(kpi.get("name", "").strip().lower())
            
    # 2. Check required dimensions
    for dim in plan.required_dimensions:
        clean_dim = dim.strip().lower()
        if clean_dim not in available_cols:
            errors.append(f"Dimension '{dim}' does not exist in the active dataset schema.")
            
    # 3. Check required metrics (permit direct columns or defined KPI metrics)
    for metric in plan.required_metrics:
        clean_metric = metric.strip().lower()
        if clean_metric not in available_cols and clean_metric not in available_kpis:
            # Let's perform a loose check to allow calculated variables like 'count(msisdn)' or custom KPI aliases,
            # but if it matches a direct misspelled name, flag it
            # (If it has standard sql aggregates like sum/count/mean, ignore to prevent false positives)
            has_agg = any(agg in clean_metric for agg in ["sum", "mean", "count", "avg", "percentage"])
            if not has_agg and clean_metric not in available_cols:
                errors.append(f"Metric/Column '{metric}' does not exist in the active schema or KPIs.")
                
    if errors:
        for err in errors:
            logger.warning(f"Plan Schema Validation Failure: {err}")
        return False, errors
        
    logger.info("Analysis plan validated successfully against schema.")
    return True, []

# ==================== PLANNER MODULE (WITH RETRY ENGINE) ====================

def generate_strategic_analysis_plan(
    query: str,
    context_profile: Dict[str, Any],
    preferred_provider: Optional[str] = None,
    max_retries: int = 3
) -> HighLevelAnalysisPlan:
    """
    Orchestrates LLM structured planning with automated schema validation and retry loops.
    
    Args:
        query: User business question.
        context_profile: Structured, token-compressed Context Profile.
        preferred_provider: LLM provider choice.
        max_retries: Maximum attempts to self-correct validation errors.
        
    Returns:
        A validated HighLevelAnalysisPlan.
    """
    logger.info(f"Generating strategic blueprint for user question: '{query}'")
    
    context_json = json.dumps(context_profile, indent=2)
    prompt = PLANNER_PROMPT_TEMPLATE.format(context_json=context_json, query=query)

    # If this goal matches a known strategy playbook, give the planner a proven
    # sequence to adapt (it still validates every step against the actual schema).
    from src.llm.playbooks import match_playbook, format_playbook
    playbook = match_playbook(query)
    if playbook:
        prompt += "\n\n" + format_playbook(playbook)

    attempt = 0
    feedback = ""
    
    while attempt < max_retries:
        attempt += 1
        logger.info(f"Planning generation attempt {attempt} of {max_retries}...")
        
        current_prompt = prompt
        if feedback:
            # Inject validation error history for self-correction
            current_prompt += f"\n\n[RETRY ATTEMPT] Your previous plan failed schema validation with these errors:\n{feedback}\nPlease correct your choices to use ONLY existing columns and dimensions."
            
        try:
            # Generate structured response from active LLM provider
            plan: HighLevelAnalysisPlan = llm_client.generate_structured_output(
                prompt=current_prompt,
                response_model=HighLevelAnalysisPlan,
                system_prompt=PLANNER_SYSTEM_PROMPT,
                provider=preferred_provider
            )
            
            # Validate output columns
            is_valid, validation_errors = validate_plan_schema(plan, context_profile)
            if is_valid:
                logger.info("Strategic analysis plan created and validated successfully.")
                return plan
                
            # Log failure and update feedback loop
            feedback = "\n".join(validation_errors)
            logger.warning(f"Attempt {attempt} failed validation checks.")
            
        except Exception as e:
            logger.error(f"Error during planning attempt {attempt}: {str(e)}")
            feedback = f"API Error: {str(e)}"
            
    # Fallback plan if all retries fail
    logger.error("All planning retry attempts exhausted. Synthesizing fallback plan...")
    fallback_plan = HighLevelAnalysisPlan(
        thought_process="Logical fallback strategy triggered due to schema validation constraints.",
        analysis_plan=["exploratory_data_profiling"],
        required_metrics=[],
        required_dimensions=[],
        suggested_visualizations=["Summary overview table"],
        recommended_statistical_tests=[],
        confidence_requirements="low"
    )
    return fallback_plan
