from pydantic import BaseModel, Field
from typing import List, Optional, Literal

class VisualSpec(BaseModel):
    """
    Structured specification for rendering Plotly charts.
    Helps separate analytical computations from visualization definitions.
    """
    is_visual_requested: bool = Field(
        ..., 
        description="True if the user's query requests or would benefit from a visual representation (chart/graph)."
    )
    chart_type: Optional[Literal["bar", "line", "scatter", "pie", "histogram", "box", "heatmap"]] = Field(
        None, 
        description="The type of chart to generate."
    )
    x_column: Optional[str] = Field(
        None, 
        description="The name of the column to plot on the X-axis."
    )
    y_column: Optional[str] = Field(
        None, 
        description="The name of the column to plot on the Y-axis."
    )
    group_column: Optional[str] = Field(
        None, 
        description="Optional column to group or color by (for multiple series)."
    )
    title: Optional[str] = Field(
        None, 
        description="The title of the chart."
    )
    x_label: Optional[str] = Field(
        None, 
        description="Custom label for the X-axis."
    )
    y_label: Optional[str] = Field(
        None, 
        description="Custom label for the Y-axis."
    )
    barmode: Optional[Literal["group", "stack"]] = Field(
        "group", 
        description="Bar mode layout if chart_type is bar."
    )
    orientation: Optional[Literal["v", "h"]] = Field(
        "v", 
        description="Orientation of bars if chart_type is bar ('v' for vertical, 'h' for horizontal)."
    )

class StatisticalResult(BaseModel):
    test_name: str
    statistic: float
    p_value: float
    effect_size: Optional[float]
    effect_size_label: Optional[str]
    is_significant: bool
    interpretation: str


class AnalysisPlan(BaseModel):
    """
    Structured plan generated by the LLM containing the logical steps, 
    the secure Pandas execution script, and visual rendering details.
    """
    thought_process: str = Field(
        ..., 
        description="Detailed step-by-step reasoning behind the chosen analysis approach."
    )
    pandas_code: str = Field(
        ..., 
        description=(
            "Valid python script doing the pandas data transformations. "
            "It must load 'df' (already pre-loaded in the global namespace), "
            "perform aggregations/filters, and assign the final aggregated dataframe to a variable named 'result_df'. "
            "Keep the result_df small and aggregated. DO NOT import forbidden packages."
        )
    )
    visual_spec: VisualSpec = Field(
        ..., 
        description="Visual chart specification corresponding to the aggregated results."
    )
    statistical_tests: Optional[List[str]] = None
    confidence_target: Optional[float] = None

class InsightInterpretation(BaseModel):
    """
    Structured response generated by the LLM summarizing the findings,
    extracting business insights, and making domain-level recommendations.
    """
    direct_answer: str = Field(
        ..., 
        description="A direct, concise, and mathematically accurate answer to the user's business question."
    )
    insights: List[str] = Field(
        ..., 
        description="Bullet-point list of high-value business insights, trends, outliers, or patterns found in the data."
    )
    recommendations: List[str] = Field(
        ..., 
        description="Bullet-point list of actionable strategic recommendations based on the findings."
    )
    confidence_score: float
    statistical_backing: Optional[List[str]] = None
